### PR TITLE
Bash refx

### PR DESCRIPTION
**Pull request by cartercanedy**
create an echo polyfill and removes echo -e flag bashism from all scripts

### CODE REVIEW

**Comment by nnyyxxxx** [comment]
Removing -e for all of the echos is not a good way to remove the bashism, removing -e will not work for bash; though it will work in posix compliant shells.

**Comment by cartercanedy** [comment]
did you look at my fix?

**Comment by cartercanedy** [comment]
I realize this, that's why I made a polyfill

**Comment by nnyyxxxx** [comment]
These problems in this PR are already solved with the 

> did you look at my fix?

Yeah, I took a look. All of the issues in this diff are already solved with the remove every bashism merge.

**Comment by cartercanedy** [comment]
I just saw that, closing

**Pull request closed without merging**
